name: 'Maximie space'
description: 'Try to maximize available space by removing unneeded software packages from Github runners'

runs:
  using: 'composite'
  steps:

  - name: Maximize build space
    shell: bash
    run: |
        echo "Disk usage before"
        echo "========================"
        df -h
        echo "Space used by toolchain"
        echo "-------------------------"
        du -h --max-depth=2 /opt || true
         echo "Space used by sw packages"
        echo "-------------------------"
        du -h --max-depth=2 /__t || true
        # Remove sw packages
        if [ -d "/__t" ]; then
          sudo rm -fr /__t/PyPy || true
          sudo rm -fr /__t/node || true
          sudo rm -fr /__t/CodeQL || true
          sudo rm -fr /__t/Ruby || true
          sudo rm -fr /__t/go || true
        fi
        if [ -d "/opt/hostedtoolcache" ]; then
          sudo rm -fr /opt/hostedtoolcache/PyPy || true
          sudo rm -fr /opt/hostedtoolcache/node || true
          sudo rm -fr /opt/hostedtoolcache/CodeQL || true
          sudo rm -fr /opt/hostedtoolcache/Ruby || true
          sudo rm -fr /opt/hostedtoolcache/go || true
          sudo rm -fr /opt/google/chrome || true
          sudo rm -fr /opt/microsoft || true
          sudo rm -fr /opt/az || true
        fi
        echo "Disk usage after"
        echo "========================"
        df -h
