name: Test Show Telemetry

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/actions/show_telemtery/**'
  push:
    branches: [ "main" ]

jobs:
  test-telemetry:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { "runs-on": "ubuntu-latest" }
          - { "runs-on": "ubuntu-22-04", "image": "ghcr.io/tenstorrent/tt-forge-fe/tt-forge-fe-ci-ubuntu-22-04:dt-8ee183d6fc5ceb4feb9feff9b2674560c43d8a00b38c7b892449220a1d3d5691" }
          - { "runs-on": "ubuntu-22.04", "image": "ubuntu:22.04" }
          - { "runs-on": "ubuntu-24.04", "image": "ubuntu:24.04" }

    runs-on: ${{ matrix.config.runs-on }}
    container:
      image: ${{ matrix.config.image }}
      volumes:
        - /proc:/host/proc:ro

    steps:
      - uses: actions/checkout@v4

      - name: Start telemetry collection
        id: telemetry_start
        uses: ./.github/actions/show_telemtery
        with:
          start_collection: true
          sampling_rate: 5
          telemetry_path: 'telemetry'
          proc_path: ${{ matrix.config.image && '/host/proc' || '/proc' }}

      - name: Simulate Network Load
        run: |
          sleep 5
          echo "Simulating network load..."
          for i in {1..20}; do
            curl -s -o /dev/null https://github.com &
            sleep 1
          done
          sleep 5

      - name: End telemetry collection
        id: telemetry_end
        uses: ./.github/actions/show_telemtery
        with:
          finish_collection: true
          telemetry_path: 'telemetry'

      - name: Upload Telemetry Data
        uses: actions/upload-artifact@v4
        with:
          name: telemetry-data-${{ matrix.config.runs-on }}-${{ matrix.config.image }}
          path: telemetry
