name: Test Show Telemetry

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/actions/show_telemtery/**'
  push:
    branches: [ "main" ]

jobs:
  test-telemetry:
    strategy:
      matrix:
        config:
          - { "runs-on": "ubuntu-latest" }
          # - { "runs-on": "ubuntu-latest", "image": "python:3.10" }

    runs-on: ${{ matrix.config.runs-on }}
    container:
      image: ${{ matrix.config.image }}
      volumes:
        - /proc:/host/proc:ro

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Start telemetry collection
        id: telemetry_start
        uses: ./.github/actions/show_telemtery
        with:
          start_collection: true
          sampling_rate: 5
          telemetry_path: 'telemetry'
          proc_path: ${{ matrix.config.image && '/host/proc' || '/proc' }}

      - name: Simulate CPU Load
        run: |
          echo "Simulating CPU load..."
          for i in {1..3}; do
            dd if=/dev/zero of=/dev/null bs=1M count=4096 &
            pids[${i}]=$!
          done
          sleep 30
          for pid in ${pids[*]}; do
            kill -9 $pid 2>/dev/null || true
          done

      - name: Simulate Memory Load
        run: |
          echo "Simulating memory load..."
          python3 -c '
          import array
          # Allocate ~500MB of memory
          data = array.array("i", [0] * (500 * 1024 * 1024 // 4))
          print(f"Allocated ~500MB of memory")
          import time
          time.sleep(15)
          ' &
          sleep 20

      - name: Simulate Disk Load
        run: |
          echo "Simulating disk load..."
          dd if=/dev/zero of=largefile bs=1M count=1024
          sleep 5
          rm largefile

      - name: Simulate Network Load
        run: |
          echo "Simulating network load..."
          for i in {1..20}; do
            curl -s -o /dev/null https://github.com &
            sleep 1
          done
          sleep 10

      - name: End telemetry collection
        id: telemetry_end
        uses: ./.github/actions/show_telemtery
        with:
          finish_collection: true
          telemetry_path: 'telemetry'

      - name: Upload Telemetry Data
        uses: actions/upload-artifact@v4
        with:
          name: telemetry-data-${{ matrix.config.image && 'container' || 'host' }}
          path: telemetry
